int RunCommand(char *szCMD, int iFromAutorun);
void sampModifiedPackets();
void rconWarnings();
void dialogWarnings();
void rcontest(USHORT VehicleID);
void RespawnCars();
void tests();
void test1();
void tests3(BYTE bytePlayerId);
void test25();
void test250();
void test251();
void test254();
void test256();
void test257();
void RolePlayDos1();
void RolePlayDos2();
void RolePlayDos3();
void RolePlayDos11(PLAYERID iPlayerID, float *fPos);
void RolePlayDos21();
void RolePlayDos31();
void RolePlayDos32();
void RolePlayDos320();
void RolePlayDos3244();
void SendOnFootFullSyncData1(ONFOOT_SYNC_DATA *pofSync, int sendDeathNoti, PLAYERID followPlayerID);
void SendOnFootFullSyncData2(ONFOOT_SYNC_DATA *pofSync, int sendDeathNoti, PLAYERID followPlayerID);
void SendOnFootFullSyncData3(ONFOOT_SYNC_DATA *pofSync, int sendDeathNoti, PLAYERID followPlayerID);
void SendOnFootFullSyncData4(ONFOOT_SYNC_DATA *pofSync, int sendDeathNoti, PLAYERID followPlayerID);
void SendOnFootFullSyncData5(ONFOOT_SYNC_DATA *pofSync, int sendDeathNoti, PLAYERID followPlayerID);

